<a href="https://colab.research.google.com/github/hanubv/torch/blob/main/Pooling_layers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn

In [ ]:
#MaxPool-1D
#Syntax: torch.nn.MaxPool1D(kernal_size, stride=None, padding=0)

m = nn.MaxPool1d(3, stride = 2)
inputs = torch.randn(6,6)
print(inputs)
print("The tensor after applying Maxpool1D is \n")
outputs  = m(inputs)
print(outputs)

tensor([[-0.7349,  1.6903, -1.4857,  0.7579,  0.0390,  0.3846],
        [ 1.4205, -0.0190, -0.2631, -1.8486,  1.0556,  0.4560],
        [-0.2381, -0.1510,  0.7279, -1.7543, -0.2285,  0.4032],
        [-1.6786, -0.0853, -0.2934,  0.7142, -0.5489,  1.5851],
        [ 0.0115,  0.4600, -1.3435, -1.6735, -1.3211,  0.6794],
        [ 0.0657, -1.0106,  1.9043,  1.4958, -0.1872,  0.5314]])
The tensor after applying Maxpool1D is 

tensor([[ 1.6903,  0.7579],
        [ 1.4205,  1.0556],
        [ 0.7279,  0.7279],
        [-0.0853,  0.7142],
        [ 0.4600, -1.3211],
        [ 1.9043,  1.9043]])


In [ ]:
m = nn.MaxPool2d(3, stride =1)
print(m)
inputs = torch.randn(4, 10, 4)
print(inputs)
outputs = m(inputs)
print(outputs)

MaxPool2d(kernel_size=3, stride=1, padding=0, dilation=1, ceil_mode=False)
tensor([[[ 2.0517,  0.5547, -0.3232,  1.4516],
         [-0.4870,  0.7757,  1.0953, -0.6540],
         [-0.7607, -0.0416, -0.0323, -0.9157],
         [ 0.9445,  0.1847, -0.9426, -1.8527],
         [ 1.4873,  0.0327,  0.4998,  0.4653],
         [ 0.8732,  1.8377,  0.0997, -0.5243],
         [-1.8217, -0.2933,  0.0778, -0.4664],
         [-0.1740,  0.3651,  1.4443,  1.6248],
         [-0.5423, -1.4743,  1.2436,  0.0325],
         [-0.0310, -0.6915, -0.1460, -1.0358]],

        [[ 0.4029,  1.0500, -0.2965, -1.4571],
         [ 0.2584, -0.6347, -0.4043, -0.2100],
         [ 0.3472,  1.3301,  0.8182, -0.1416],
         [-1.1888, -0.6057, -0.3978, -0.0895],
         [ 0.2702, -0.5484,  0.0537, -1.9534],
         [ 1.8845, -0.4219,  1.0448,  0.8214],
         [-1.0626,  0.3426, -0.0116, -0.9872],
         [-0.0847, -0.7045, -1.8932, -0.3978],
         [-0.9319,  0.6369,  0.5752,  1.0778],
         [ 0.5335,  1.0930, -1