<a href="https://colab.research.google.com/github/hanubv/torch/blob/main/torch_non_linear_activations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn

In [ ]:
#ELU- Exponential Linear Unit
#Syntax: torch.nn.ELU(alpha = 1.0, inplace= bool)
#Example:
m = nn.ELU()
inputs = torch.randn(2)
print(inputs)
outputs = m(inputs)
print(outputs)

tensor([-1.9239, -1.2277])
tensor([-0.8540, -0.7070])


In [ ]:
#Hardshrink activation
#Syntax: torch.nn.Hardshrink(lamda=0.5)
#example:
m = nn.Hardshrink()
inputs = torch.randn(2)
print(inputs)
outputs = m(inputs)
print(outputs)

tensor([0.2106, 0.9303])
tensor([0.0000, 0.9303])


In [ ]:
#Hardsigmoid Activation
#Syntax: torch.nn.Hardsigmoid(inplace = False)
#Example:
m = nn.Hardsigmoid()
inputs = torch.randn(2)
print(inputs)
outputs = m(inputs)
print(outputs)

tensor([0.1234, 0.5599])
tensor([0.5206, 0.5933])


In [ ]:
#HardTanH Activation
#syntax: torch.nn.Hardtanh(min_values = -1, max_value = 1, inplace = bool)
#Example:
m = nn.Hardtanh(-2, 2)
inputs = torch.randn(2, 10)
print(inputs)
outputs = m(inputs)
print(outputs)

tensor([[-0.3187,  0.2429, -0.2304, -1.0415,  0.4975, -0.2751, -0.9131,  0.1001,
          1.0210, -0.1435],
        [ 0.0196, -0.2500, -0.3773,  0.3193,  0.7646,  2.0715,  0.0671, -0.3972,
          1.1680, -1.5815]])
tensor([[-0.3187,  0.2429, -0.2304, -1.0415,  0.4975, -0.2751, -0.9131,  0.1001,
          1.0210, -0.1435],
        [ 0.0196, -0.2500, -0.3773,  0.3193,  0.7646,  2.0000,  0.0671, -0.3972,
          1.1680, -1.5815]])


In [ ]:
#Leaky ReLU Activation
"""
Mathematical representation of leaky relu
LeakyReLU(x) = max(0, x)+negative_slope*min(0,x)
Synatx: torch.nn.LeakyReLU(negative_slope = 0.01, inplace = bool)
"""
#Example:
m = nn.LeakyReLU(0.01)
inputs = torch.randn(2)
print(inputs)
outputs = m(inputs)
print(outputs)

tensor([-0.0726, -1.1147])
tensor([-0.0007, -0.0111])


In [ ]:
#LogSimoid activation function
"""
The Mathematical representation for logsigmoid activation function is
LogSigmoid(x) = 1/1+exp(-1)
Syntax: torch.nn.LogSigmoid(*args, **kwargs)
"""
#Example:
m = nn.LogSigmoid()
inputs = torch.randn(2)
print(inputs)
outputs = m(inputs)
print(outputs)

tensor([ 0.5504, -1.3586])
tensor([-0.4553, -1.5874])


In [ ]:
#Parameterised ReLU activation function
"""
The mathematical representation of parameterised relu can be shown as below
PReLU(x) = max(0, x)+a*min(0, x)
syntax = torch.nn.PReLU()
"""
#Example:
m = nn.PReLU()
inputs = torch.randn(2)
print(inputs)
outputs = m(inputs)
print(outputs)

tensor([-2.8286,  0.0981])
tensor([-0.7072,  0.0981], grad_fn=<PreluKernelBackward0>)


In [ ]:
#ReLU Activation fucntion
"""
Applies ReLU activation function over all the inputs elementwise
The mathematical representation of ReLU can be shown as below
ReLu(x) = max(0, x)
Syntax: torch.nn.ReLU(inplace = False)
"""
#Example:
m = nn.ReLU()
inputs = torch.randn(2)
print(inputs)
outputs = m(inputs)
print(outputs)

tensor([ 0.2027, -0.3669])
tensor([0.2027, 0.0000])


In [ ]:
#Sigmoid Activation Function
"""
The mathematical representation of sigmoidal fucntion can be shown as below.
Sigmoid(x) = 1/(1+exp(-x))
Syntax:torch.nn.Sigmoid(*args, **kwargs)
"""
#example:
m = nn.Sigmoid()
inputs = torch.randn(2)
print(inputs)
outputs = m(inputs)
print(outputs)

tensor([-0.2966,  0.3475])
tensor([0.4264, 0.5860])


In [ ]:
#TanH Activation Function
"""
Applies hyperbolic tangent fucntion elementwise on input
The mathematical representation of TanH function can be shown as
Tanh(x) = (exp(x)-exp(-x))/(exp(x)+exp(-x))
syntax: torch.nn.Tanh(*args, **kwargs)
"""
#Syntax:
m = nn.Tanh()
inputs = torch.randn(2)
print(inputs)
ouputs = m(inputs)
print(outputs)


tensor([-0.6292,  0.8813])
tensor([0.4264, 0.5860])


In [ ]:
#SoftMin activation function
"""
Applies Softmin activation to n-dimensional input tensor and rescaling them so that the output of n-dimensional lies with in the range of (0, 1) and sums to 1
The mathematical representation fo Softmin activation function can be shown as below
Softmin(x) = exp(-x)/sum(exp(-x))
syntax: torch.nn.Softmin(dim = none)
"""
#Example
m = nn.Softmin(dim=1)
inputs = torch.randn(2,2)
print(inputs)
ouputs = m(inputs)
print(outputs)


tensor([[ 0.6383, -0.0618],
        [-0.8419,  0.9201]])
tensor([0.4264, 0.5860])


In [ ]:
#SoftMax activation function
"""
Applies Softmax activation to n-dimensional input tensor and rescaling them so that the output of n-dimensional lies with in the range of (0, 1) and sums to 1
The mathematical representation fo Softmax activation function can be shown as below
Softmax(x) = exp(x)/sum(exp(x))
syntax: torch.nn.Softmax(dim = none)
"""
#Example
m = nn.Softmax(dim= 1)
inputs = torch.randn(2,2)
print(inputs)
outputs = m(inputs)
print(outputs)

tensor([[ 0.8739,  0.0778],
        [-0.6867, -0.6733]])
tensor([[0.6891, 0.3109],
        [0.4967, 0.5033]])


In [ ]:
#Softmax2D
"""
Softmax2d applies over features in each loacation if given input image is having channels, height and width then softmax function will be applied on each loaction
(Channels, height, width)
Syntax:
torch.nn.Softmax2d(*args, **kwargs)
"""
#Example:
m = nn.Softmax2d()
inputs = torch.randn(2, 3, 12)
print(inputs)
outputs = m(inputs)
print(outputs)

tensor([[[ 0.7557, -0.4461,  1.1434,  0.0063, -0.4778,  1.6566, -0.7878,
          -1.1018, -0.5400,  0.8439, -0.4263,  0.8545],
         [-1.2879,  0.5243,  1.1545,  0.3117, -0.7260,  0.3276, -0.2623,
          -1.2575, -0.0736,  0.2189, -0.2590,  0.8629],
         [-1.8271,  0.1600,  0.5989,  0.7941, -0.3992,  0.8186, -1.4618,
           0.0214,  1.5286,  0.8333, -0.9580,  2.1688]],

        [[-0.9112,  0.2107,  0.9831,  0.3755, -0.2410, -0.0062,  0.0242,
           2.1633,  0.1958, -0.6860,  1.0918,  0.8691],
         [-0.1948,  0.5144, -0.6221,  0.9815, -1.2554,  1.8999, -0.1630,
           0.5094, -1.2041,  1.1137,  0.4256, -1.2007],
         [-0.2924, -0.3040,  0.7996, -1.2166, -2.2271,  1.2668,  1.1329,
           1.2308,  1.4826, -0.6486, -0.1821, -0.1981]]])
tensor([[[0.8412, 0.3414, 0.5400, 0.4087, 0.4411, 0.8406, 0.3075, 0.0368,
          0.3239, 0.8220, 0.1797, 0.4963],
         [0.2510, 0.5025, 0.8553, 0.3385, 0.6294, 0.1719, 0.4752, 0.1459,
          0.7559, 0.2901, 0.335