<a href="https://colab.research.google.com/github/hanubv/torch/blob/main/torch_convolution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn

# **Conv1D**
Conv1d applies 1dimensional convolution on inputs layers composed of several input planes.
In the simplest case, the input of layer is (N, Cin, L) and ouput can be represented as (N, Cout, Lout) and representation can be showna as

out(N, Cout) = bias(Cout)+sum(weights(Cout, k)*input(Ni, k)

where:
N is input batch size

C is number of channels

*-operator is cross correlation or mulitplication operator and

L denoted length of the signal sequence


#Syntax:
torch.nn.Conv1d(int_channels, out_channels, kernal_size, stride=1, padding = 0, dilation = 0)

In [ ]:
m = nn.Conv1d(16, 33, 3, stride = 2)
print(m)
inputs = torch.randn(20, 16, 50)
#print(inputs)
print("\n")
ouput = m(inputs)
print(ouput)

Conv1d(16, 33, kernel_size=(3,), stride=(2,))


tensor([[[ 4.0294e-01,  2.1837e-01, -5.3386e-02,  ...,  7.5416e-01,
           7.3308e-01, -6.7935e-01],
         [ 1.0518e-01,  2.5885e-01,  2.9104e-01,  ...,  1.7675e-01,
           2.6751e-01, -5.0886e-01],
         [ 1.7165e-01,  2.0158e-01, -1.2271e+00,  ..., -5.0281e-01,
           2.7088e-01, -1.2380e+00],
         ...,
         [-6.4546e-02, -3.4063e-01,  1.0534e+00,  ..., -4.7354e-01,
          -1.0647e+00,  8.7044e-01],
         [ 6.0654e-01,  1.5295e-01,  1.9020e-01,  ...,  2.8372e-01,
           1.0453e-01, -1.2174e+00],
         [-7.8301e-01, -6.5491e-01,  4.3706e-02,  ...,  7.1671e-01,
          -2.5592e-01,  9.8264e-02]],

        [[ 4.7850e-01, -3.3524e-01,  3.7793e-01,  ...,  9.9506e-01,
          -7.2145e-01,  6.0176e-01],
         [ 6.6339e-01,  2.5685e-01, -4.3390e-01,  ...,  8.6779e-02,
          -4.1629e-01, -3.6216e-01],
         [ 1.7359e+00, -1.0129e+00,  5.9969e-01,  ...,  1.1869e-01,
           3.4310e-01,  1.02

In [ ]:
#CONV2D
#Syntax: torch.nn.Conv2d(in_channels, out_channels, kernal_size, stride)
#onv2d function with square size kernals
m = nn.Conv2d(16, 33, 3, stride = 2)
print(m)
inputs = torch.randn(20, 16, 50, 10)
print(inputs)
#output = m(inputs)
print(ouput)


Conv2d(16, 33, kernel_size=(3, 3), stride=(2, 2))
tensor([[[[ 7.2564e-01, -1.1817e+00,  3.3685e-01,  ...,  7.4125e-01,
            8.3961e-01,  3.9589e-02],
          [ 3.2250e-01, -2.5979e+00,  7.3402e-01,  ..., -5.0451e-01,
           -2.2929e-01, -5.0721e-01],
          [-1.4411e-01, -3.3909e-01, -4.7078e-01,  ...,  1.0852e+00,
           -1.0323e+00, -5.3045e-02],
          ...,
          [ 8.5049e-01,  1.1516e+00, -1.7545e-01,  ..., -1.8895e+00,
            9.0279e-01, -2.7410e-01],
          [ 3.5989e-01, -6.9243e-01,  2.9173e-03,  ..., -1.6299e+00,
            2.3994e+00,  1.4753e-01],
          [ 1.6035e+00,  4.9615e-01,  1.0608e+00,  ..., -1.4413e+00,
           -4.4974e-01,  7.3489e-01]],

         [[ 8.8401e-01, -9.2808e-01, -5.8327e-02,  ...,  1.4671e+00,
           -1.1631e+00, -1.5953e+00],
          [ 5.1567e-01, -3.6636e-01, -8.9255e-01,  ...,  3.5348e-01,
           -7.1628e-01, -3.7980e-01],
          [ 7.4593e-02, -1.1942e+00, -4.0560e-01,  ..., -9.9354e-01,
        

In [ ]:
#Conv2d function with non square filters, unequal striding, and with padding
m = nn.Conv2d(16,33, (3,4), stride = (2,1), padding = (4,2))
print(m)
inputs = torch.randn(2,16, 6, 10)
#print(inputs)
outputs = m(inputs)
print(outputs)

Conv2d(16, 33, kernel_size=(3, 4), stride=(2, 1), padding=(4, 2))
tensor([[[[-2.6649e-02, -2.6649e-02, -2.6649e-02,  ..., -2.6649e-02,
           -2.6649e-02, -2.6649e-02],
          [-1.0074e-01,  3.1165e-01, -4.9204e-01,  ...,  7.0974e-01,
            3.3363e-02, -5.9344e-02],
          [-8.7869e-02, -6.6926e-01, -1.3162e+00,  ..., -3.5006e-01,
           -4.9967e-04,  1.1353e+00],
          [-8.9962e-01, -3.5231e-01,  5.5593e-02,  ...,  2.8077e-01,
            6.9886e-01,  1.9530e-01],
          [ 1.4163e-01,  8.6857e-01, -8.9678e-01,  ...,  5.3091e-02,
           -4.3930e-02, -9.4312e-02],
          [-2.6649e-02, -2.6649e-02, -2.6649e-02,  ..., -2.6649e-02,
           -2.6649e-02, -2.6649e-02]],

         [[ 1.0418e-02,  1.0418e-02,  1.0418e-02,  ...,  1.0418e-02,
            1.0418e-02,  1.0418e-02],
          [-1.1745e-01, -2.4076e-01,  1.5691e-01,  ..., -2.5237e-01,
           -6.4543e-02,  6.9900e-01],
          [ 4.4395e-01, -2.3437e-02,  5.6764e-01,  ..., -5.3386e-01,
       