<a href="https://colab.research.google.com/github/hanubv/torch/blob/main/torch_loss_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn
import matplotlib.pyplot as plt


In [ ]:
# NN.L1Loss
"""
creates a criterion that measures the mean absolute error between each elements in inputs and outputs.
Syntax:
torch.nn.L1Loss(size_average = None, reduce = None, reduction = 'mean')
"""
#Example
loss = nn.L1Loss()
inputs = torch.randn(3, 4, requires_grad = True)
print(inputs)
targets = torch.randn(3, 4)
output = loss(inputs, targets)
print("\n")
print(output)
print(output.backward())




tensor([[ 1.0071, -0.5442, -1.7728, -0.8512],
        [-0.1091, -1.3962, -0.1515, -1.3668],
        [-0.0619, -0.7485,  1.6045, -1.4087]], requires_grad=True)


tensor(1.1494, grad_fn=<MeanBackward0>)
None


In [ ]:
#MSELoss
"""
The mathematical representation for mean squared error can be shown as below
MSE = 1/n * (sum(y_pred - y_actual)**2)
Syntax:
torch.nn.MSELoss(average_size = None, reduce = None, reduction = 'mean')
"""
#Example:
mse_loss = nn.MSELoss()
inputs = torch.randn(3, 5, requires_grad = True)
print(inputs)
targets = torch.randn(3, 5)
print("\n")
print(targets)
output = mse_loss(inputs, targets)
print(output)

output = output.backward()
print(output)


tensor([[ 0.8892, -0.0692, -0.2788, -0.6251, -2.1837],
        [ 0.6984,  0.7830,  0.2969,  1.0064, -0.8268],
        [-0.4605,  1.5333,  0.2893, -1.8493, -0.6117]], requires_grad=True)


tensor([[ 1.0018,  0.2787, -0.6640,  1.5737, -0.8717],
        [ 0.9479,  1.9852,  0.6449, -0.8312, -0.8116],
        [ 0.6414,  0.0258, -0.9586,  0.2695,  0.9641]])
tensor(1.5907, grad_fn=<MseLossBackward0>)
None


In [ ]:
#Cross entropy loss
"""
Cross entropy loss computes the loss between inputs and logits
syntax:
torch.nn.CrossEntropyLoss(average_size = none, reduce = None, reduction = 'mean')
"""
# Example of target with class indices:
cross_entropy_loss = torch.nn.CrossEntropyLoss()
inputs = torch.randn(3, 5, requires_grad = True)
print(inputs)

targets = torch.randn(3, 5)
print("\n")
print(targets)

output = cross_entropy_loss(inputs, targets)
print(output)

output = output.backward()
print(output)


tensor([[ 0.1037, -1.5625, -0.5657,  1.7726,  1.0235],
        [ 0.1817,  0.1479,  0.4882, -0.3711, -0.3139],
        [ 0.8278,  1.7231,  1.1138, -1.4935, -0.4828]], requires_grad=True)


tensor([[ 0.3939,  0.8411, -1.7295, -0.4820,  0.0182],
        [-0.2533,  0.6137, -0.6373,  0.7880, -0.4630],
        [-0.7219,  0.1203,  0.6310,  1.3696, -0.4813]])
tensor(1.0436, grad_fn=<DivBackward1>)
None


In [ ]:
# Example of target with class probabilities
cse = torch.nn.CrossEntropyLoss()
inputs = torch.randn(3, 5, requires_grad = True)
print("Inputs")
print(inputs)
targets = torch.randn(3, 5).softmax(dim= 1)
print("\n")
print("Targets with softmax fucntion")
print(targets)
outputs = cse(inputs, targets)
print("\n")
print("The loss function output")
print(outputs)
outputs = outputs.backward()
print(outputs)

Inputs
tensor([[-0.7547,  0.4718,  0.3194, -0.4614, -0.9709],
        [ 0.4970, -0.2638,  0.4181,  0.1082,  0.2175],
        [-0.7543,  1.0800,  0.9305,  0.5290, -0.2645]], requires_grad=True)


Targets with softmax fucntion
tensor([[0.3813, 0.0891, 0.3498, 0.1598, 0.0199],
        [0.0755, 0.2543, 0.3841, 0.2565, 0.0296],
        [0.3975, 0.2735, 0.0072, 0.1971, 0.1247]])


The loss function output
tensor(1.8173, grad_fn=<DivBackward1>)
None


In [ ]:
#Negative Log Liklihood loss function
